    package ventanas;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.WindowConstants;
import java.sql.*;
import clases.Conexion;
import javax.swing.JOptionPane;

public class AnadirUsuario extends javax.swing.JFrame {

    String usuario;

    public AnadirUsuario() {
        initComponents();

        usuario = Login.usuario;

        setTitle("Añadir nuevo usuario - Sesión de " + usuario);
        setSize(800, 550);
        setResizable(false);
        setLocationRelativeTo(null);

        //Este método hace que el programa principal siga en ejecución despues de cerrar esta interfaz
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        //Imagen de fondo
        ImageIcon wallpaper = new ImageIcon("src/images/Wallpaper.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel_Wallpaper.getWidth(), jLabel_Wallpaper.getHeight(), Image.SCALE_DEFAULT));
        jLabel_Wallpaper.setIcon(icono);
        this.repaint();
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/logo/icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2_password = new javax.swing.JLabel();
        jLabel3apellidos = new javax.swing.JLabel();
        jLabel4_nombre = new javax.swing.JLabel();
        jLabel5_username = new javax.swing.JLabel();
        jLabel6_email = new javax.swing.JLabel();
        jLabel7_puesto = new javax.swing.JLabel();
        jLabel8_tlf = new javax.swing.JLabel();
        jButton_anadir = new javax.swing.JButton();
        jLabel1_titulo = new javax.swing.JLabel();
        txt_apellidos = new javax.swing.JTextField();
        txt_tlf = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_username = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        combo_puesto = new javax.swing.JComboBox<>();
        btn_limpiar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        jLabel_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2_password.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        jLabel2_password.setForeground(new java.awt.Color(29, 33, 123));
        jLabel2_password.setText("Password:");
        getContentPane().add(jLabel2_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, -1, -1));

        jLabel3apellidos.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        jLabel3apellidos.setForeground(new java.awt.Color(29, 33, 123));
        jLabel3apellidos.setText("Apellidos:");
        getContentPane().add(jLabel3apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jLabel4_nombre.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        jLabel4_nombre.setForeground(new java.awt.Color(29, 33, 123));
        jLabel4_nombre.setText("Nombre:");
        getContentPane().add(jLabel4_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel5_username.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        jLabel5_username.setForeground(new java.awt.Color(29, 33, 123));
        jLabel5_username.setText("Username:");
        getContentPane().add(jLabel5_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, -1, -1));

        jLabel6_email.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        jLabel6_email.setForeground(new java.awt.Color(29, 33, 123));
        jLabel6_email.setText("E-mail:");
        getContentPane().add(jLabel6_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        jLabel7_puesto.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        jLabel7_puesto.setForeground(new java.awt.Color(29, 33, 123));
        jLabel7_puesto.setText("Puesto:");
        getContentPane().add(jLabel7_puesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 425, -1, -1));

        jLabel8_tlf.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        jLabel8_tlf.setForeground(new java.awt.Color(29, 33, 123));
        jLabel8_tlf.setText("Teléfono:");
        getContentPane().add(jLabel8_tlf, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        jButton_anadir.setBackground(new java.awt.Color(255, 255, 255));
        jButton_anadir.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        jButton_anadir.setForeground(new java.awt.Color(29, 33, 123));
        jButton_anadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/add.jpg"))); // NOI18N
        jButton_anadir.setBorder(null);
        jButton_anadir.setBorderPainted(false);
        jButton_anadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_anadirActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_anadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 110, 110));

        jLabel1_titulo.setFont(new java.awt.Font("Gadugi", 1, 30)); // NOI18N
        jLabel1_titulo.setForeground(new java.awt.Color(29, 33, 123));
        jLabel1_titulo.setText("Añadir nuevo usuario");
        getContentPane().add(jLabel1_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        txt_apellidos.setBackground(new java.awt.Color(240, 240, 240));
        txt_apellidos.setFont(new java.awt.Font("Gadugi", 0, 16)); // NOI18N
        txt_apellidos.setForeground(new java.awt.Color(29, 33, 123));
        txt_apellidos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 200, 200, -1));

        txt_tlf.setBackground(new java.awt.Color(240, 240, 240));
        txt_tlf.setFont(new java.awt.Font("Gadugi", 0, 16)); // NOI18N
        txt_tlf.setForeground(new java.awt.Color(29, 33, 123));
        txt_tlf.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_tlf, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 250, 200, -1));

        txt_email.setBackground(new java.awt.Color(240, 240, 240));
        txt_email.setFont(new java.awt.Font("Gadugi", 0, 16)); // NOI18N
        txt_email.setForeground(new java.awt.Color(29, 33, 123));
        txt_email.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 300, 200, -1));

        txt_username.setBackground(new java.awt.Color(240, 240, 240));
        txt_username.setFont(new java.awt.Font("Gadugi", 0, 16)); // NOI18N
        txt_username.setForeground(new java.awt.Color(29, 33, 123));
        txt_username.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, 200, -1));

        txt_nombre.setBackground(new java.awt.Color(240, 240, 240));
        txt_nombre.setFont(new java.awt.Font("Gadugi", 0, 16)); // NOI18N
        txt_nombre.setForeground(new java.awt.Color(29, 33, 123));
        txt_nombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 150, 200, -1));

        txt_password.setBackground(new java.awt.Color(240, 240, 240));
        txt_password.setFont(new java.awt.Font("Gadugi", 0, 16)); // NOI18N
        txt_password.setForeground(new java.awt.Color(29, 33, 123));
        txt_password.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, 200, -1));

        combo_puesto.setBackground(new java.awt.Color(240, 240, 240));
        combo_puesto.setFont(new java.awt.Font("Gadugi", 0, 16)); // NOI18N
        combo_puesto.setForeground(new java.awt.Color(29, 33, 123));
        combo_puesto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Recepcion", "Reservas" }));
        combo_puesto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(combo_puesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 200, -1));

        btn_limpiar.setBackground(new java.awt.Color(255, 255, 255));
        btn_limpiar.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        btn_limpiar.setForeground(new java.awt.Color(29, 33, 123));
        btn_limpiar.setText("Vaciar campos");
        btn_limpiar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_limpiar.setBorderPainted(false);
        btn_limpiar.setFocusPainted(false);
        btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 420, 140, 35));

        btn_cancelar.setBackground(new java.awt.Color(255, 255, 255));
        btn_cancelar.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        btn_cancelar.setForeground(new java.awt.Color(29, 33, 123));
        btn_cancelar.setText("Cancelar");
        btn_cancelar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_cancelar.setBorderPainted(false);
        btn_cancelar.setFocusPainted(false);
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 420, 100, 35));
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_anadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_anadirActionPerformed

        String username, password, nombre, apellidos, tlf, email, puesto_string = "";
        int puesto_int;
        int validacion = 0;

        username = txt_username.getText().trim();
        password = txt_password.getText().trim();
        nombre = txt_nombre.getText().trim();
        apellidos = txt_apellidos.getText().trim();
        tlf = txt_tlf.getText().trim();
        email = txt_email.getText().trim();
        puesto_int = combo_puesto.getSelectedIndex() + 1;

        //Comprobación de que todos los campos han sido rellenados
        if (username.equals("")) {
            txt_username.setBackground(new Color(255, 82, 82));
            validacion++;
        }
        if (password.equals("")) {
            txt_password.setBackground(new Color(255, 82, 82));
            validacion++;
        }
        if (nombre.equals("")) {
            txt_nombre.setBackground(new Color(255, 82, 82));
            validacion++;
        }
        if (apellidos.equals("")) {
            txt_apellidos.setBackground(new Color(255, 82, 82));
            validacion++;
        }
        if (tlf.equals("")) {
            txt_tlf.setBackground(new Color(255, 82, 82));
            validacion++;
        }
        if (email.equals("")) {
            txt_email.setBackground(new Color(255, 82, 82));
            validacion++;
        }

        //Asignando a cada valor INT del combobox un valor String para meterlo en la BD
        if (puesto_int == 1) {
            puesto_string = "Administrador";
        } else if (puesto_int == 2) {
            puesto_string = "Recepcion";
        } else if (puesto_int == 3) {
            puesto_string = "Reservas";
        }

        //Consulta para comprobar que el username elegido está disponible
        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement("select username from usuarios where username = '" + username + "'");
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                txt_username.setBackground(new Color(255, 82, 82));
                JOptionPane.showMessageDialog(null, "El nombre de usuario elegido no está disponible.");
                cn.close();
            } else {

                cn.close();

                if (validacion == 0) {
                    Connection cn2 = Conexion.conectar();
                    PreparedStatement pst2 = cn2.prepareStatement("insert into usuarios values (?,?,?,?,?,?,?,?,?)");

                    pst2.setInt(1, 0);                          //id  
                    pst2.setString(2, username);                //username
                    pst2.setString(3, password);                //password
                    pst2.setString(4, nombre);                  //nombre
                    pst2.setString(5, apellidos);               //apellidos
                    pst2.setString(6, tlf);                     //telefono
                    pst2.setString(7, puesto_string);           //puesto
                    pst2.setString(8, email);                   //email
                    pst2.setString(9, "Activo");                //estatus

                    pst2.executeUpdate(); //Ejecutar sentencia
                    cn2.close();

                    Limpiar();
                    txt_username.setBackground(new Color(188, 245, 144));
                    txt_password.setBackground(new Color(188, 245, 144));
                    txt_nombre.setBackground(new Color(188, 245, 144));
                    txt_apellidos.setBackground(new Color(188, 245, 144));
                    txt_email.setBackground(new Color(188, 245, 144));
                    txt_tlf.setBackground(new Color(188, 245, 144));

                    JOptionPane.showMessageDialog(null, "Usuario registrado correctamente.");
                    this.dispose(); //Cierra la interfaz

                } else {
                    JOptionPane.showMessageDialog(null, "Debe rellenar todos los campos.");
                }
            }

        } catch (SQLException e) {
            System.err.println("Ha ocurrido un error al consultar si el Username existe en la BD " + e);
            JOptionPane.showMessageDialog(null, "Error en la conexión con la base de datos. Contacte con el Administrador del sistema.");
        }


    }//GEN-LAST:event_jButton_anadirActionPerformed

    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarActionPerformed
        Limpiar();

        txt_username.setBackground(new Color(240, 240, 240));
        txt_password.setBackground(new Color(240, 240, 240));
        txt_nombre.setBackground(new Color(240, 240, 240));
        txt_apellidos.setBackground(new Color(240, 240, 240));
        txt_email.setBackground(new Color(240, 240, 240));
        txt_tlf.setBackground(new Color(240, 240, 240));

    }//GEN-LAST:event_btn_limpiarActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnadirUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnadirUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnadirUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnadirUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnadirUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_limpiar;
    private javax.swing.JComboBox<String> combo_puesto;
    private javax.swing.JButton jButton_anadir;
    private javax.swing.JLabel jLabel1_titulo;
    private javax.swing.JLabel jLabel2_password;
    private javax.swing.JLabel jLabel3apellidos;
    private javax.swing.JLabel jLabel4_nombre;
    private javax.swing.JLabel jLabel5_username;
    private javax.swing.JLabel jLabel6_email;
    private javax.swing.JLabel jLabel7_puesto;
    private javax.swing.JLabel jLabel8_tlf;
    private javax.swing.JLabel jLabel_Wallpaper;
    private javax.swing.JTextField txt_apellidos;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_tlf;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables

    public void Limpiar() {
        txt_username.setText("");
        txt_password.setText("");
        txt_nombre.setText("");
        txt_apellidos.setText("");
        txt_email.setText("");
        txt_tlf.setText("");
        combo_puesto.setSelectedIndex(0);
    }

}
