package ventanas;

import clases.BD;

import javax.swing.WindowConstants;

public class InfoCliente extends javax.swing.JFrame {

    int cliente;
    BD bd;

    String nombre, apellidos, DNI, pasaporte, nacionalidad, telefono, email = "";

    public InfoCliente() {
        initComponents();

        cliente = Clientes.cliente;

        setSize(800, 530);
        setResizable(false);
        setTitle("Información de cliente " + cliente);
        setLocationRelativeTo(null);

        //Evite que el programa se cierre al cerrar la ventana
        this.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        bd = new BD();

        //Muestra la info del cliente al abrir la ventana
        mostrarInfoCliente();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btn_cerrar = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();
        label_email = new javax.swing.JLabel();
        label_telefono = new javax.swing.JLabel();
        label_nacionalidad = new javax.swing.JLabel();
        label_pasaporte = new javax.swing.JLabel();
        label_dni = new javax.swing.JLabel();
        label_apellidos = new javax.swing.JLabel();
        label_nombre = new javax.swing.JLabel();
        label_id = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ID:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel3.setText("Apellidos:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel4.setText("DNI:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jLabel5.setText("Pasaporte:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jLabel6.setText("Nacionalidad:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jLabel7.setText("Telefono:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        jLabel8.setText("Email:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, -1));

        btn_cerrar.setText("Cerrar");
        btn_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 410, -1, -1));

        btn_modificar.setText("Modificar");
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 350, -1, -1));

        label_email.setText("...");
        getContentPane().add(label_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, -1, -1));

        label_telefono.setText("...");
        getContentPane().add(label_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, -1, -1));

        label_nacionalidad.setText("...");
        getContentPane().add(label_nacionalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, -1, -1));

        label_pasaporte.setText("...");
        getContentPane().add(label_pasaporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, -1, -1));

        label_dni.setText("...");
        getContentPane().add(label_dni, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        label_apellidos.setText("...");
        getContentPane().add(label_apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, -1));

        label_nombre.setText("...");
        getContentPane().add(label_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        label_id.setText("...");
        getContentPane().add(label_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_cerrarActionPerformed

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
        ModificarCliente mc = new ModificarCliente();
        mc.setVisible(true);
    }//GEN-LAST:event_btn_modificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InfoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InfoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InfoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InfoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InfoCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cerrar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel label_apellidos;
    private javax.swing.JLabel label_dni;
    private javax.swing.JLabel label_email;
    private javax.swing.JLabel label_id;
    private javax.swing.JLabel label_nacionalidad;
    private javax.swing.JLabel label_nombre;
    private javax.swing.JLabel label_pasaporte;
    private javax.swing.JLabel label_telefono;
    // End of variables declaration//GEN-END:variables

    public void mostrarInfoCliente() {
        String[] infoCliente = bd.obtenerInfoCliente(cliente);

        nombre = infoCliente[0];
        apellidos = infoCliente[1];
        DNI = infoCliente[2];
        pasaporte = infoCliente[3];
        nacionalidad = infoCliente[4];
        telefono = infoCliente[5];
        email = infoCliente[6];

        label_id.setText(String.valueOf(cliente));
        label_nombre.setText(nombre);
        label_apellidos.setText(apellidos);
        label_dni.setText(DNI);
        label_pasaporte.setText(pasaporte);
        label_nacionalidad.setText(nacionalidad);
        label_telefono.setText(telefono);
        label_email.setText(email);
    }

}
