package ventanas;
import clases.BD;
import javax.swing.WindowConstants;

public class InfoReserva extends javax.swing.JFrame {

    int reserva;
    String fecha, entrada, salida, precio, alojamiento, cliente = "";
    BD bd;

    public InfoReserva() {
        initComponents();

        reserva = Reservas.reserva;

        setSize(800, 530);
        setResizable(false);
        setTitle("Información de reserva " + reserva);
        setLocationRelativeTo(null);

        //Evita que el programa se cierre al cerrar la ventana
        this.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        bd = new BD();

        //Muestra la info de la reserva al abrir la ventana
        mostrarInfoReserva();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btn_cerrar = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();
        label_fecha = new javax.swing.JLabel();
        label_alojamiento = new javax.swing.JLabel();
        label_precio = new javax.swing.JLabel();
        label_salida = new javax.swing.JLabel();
        label_entrada = new javax.swing.JLabel();
        label_id = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        label_cliente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Reserva:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel2.setText("ID:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jLabel3.setText("Fecha realizacion:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, -1, -1));

        jLabel4.setText("Salida:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jLabel5.setText("Precio:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        jLabel6.setText("Alojamiento:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        jLabel7.setText("Cliente:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        btn_cerrar.setText("Cerrar");
        btn_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 410, -1, -1));

        btn_modificar.setText("Modificar");
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 360, -1, -1));

        label_fecha.setText("...");
        getContentPane().add(label_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 100, -1, -1));

        label_alojamiento.setText("...");
        getContentPane().add(label_alojamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));

        label_precio.setText("...");
        getContentPane().add(label_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, -1, -1));

        label_salida.setText("...");
        getContentPane().add(label_salida, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, -1, -1));

        label_entrada.setText("...");
        getContentPane().add(label_entrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));

        label_id.setText("...");
        getContentPane().add(label_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        jLabel14.setText("Entrada:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        label_cliente.setText("...");
        getContentPane().add(label_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_cerrarActionPerformed

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
        ModificarReserva mr = new ModificarReserva();
        mr.setVisible(true);
    }//GEN-LAST:event_btn_modificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InfoReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InfoReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InfoReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InfoReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InfoReserva().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cerrar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel label_alojamiento;
    private javax.swing.JLabel label_cliente;
    private javax.swing.JLabel label_entrada;
    private javax.swing.JLabel label_fecha;
    private javax.swing.JLabel label_id;
    private javax.swing.JLabel label_precio;
    private javax.swing.JLabel label_salida;
    // End of variables declaration//GEN-END:variables

    public void mostrarInfoReserva() {
        String[] infoCliente = bd.obtenerInfoReserva(reserva);

        fecha = infoCliente[0];
        entrada = infoCliente[1];
        salida = infoCliente[2];
        precio = infoCliente[3];
        alojamiento = infoCliente[4];
        cliente = infoCliente[5];

        label_id.setText(String.valueOf(reserva));
        label_fecha.setText(fecha);
        label_entrada.setText(entrada);
        label_salida.setText(salida);
        label_precio.setText(precio);
        label_alojamiento.setText(bd.obtenerNombreAlojamiento(alojamiento));
        label_cliente.setText(bd.obtenerNombreCliente(cliente));
    }

}
