package ventanas;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class Login extends javax.swing.JFrame {

    public static String usuario = "";  //Esta variable nos permitira enviar datos entre interfaces
    String pass = "";

    public Login() {
        initComponents();

        setSize(400, 550);
        setResizable(false);
        setTitle("BookingManager");
        setLocationRelativeTo(null);

        //Wallpaper
        ImageIcon wallpaper = new ImageIcon("src/images/wallpaper.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel_Wallpaper.getWidth(), jLabel_Wallpaper.getHeight(), Image.SCALE_DEFAULT));
        jLabel_Wallpaper.setIcon(icono);
        this.repaint();

        //Logo
        ImageIcon wallpaper_logo = new ImageIcon("src/images/logo/logo_small.png");
        Icon icono_logo = new ImageIcon(wallpaper_logo.getImage().getScaledInstance(jLabel_Logo.getWidth(), jLabel_Logo.getHeight(), Image.SCALE_DEFAULT));
        jLabel_Logo.setIcon(icono_logo);
        this.repaint();
    }

    //Icono de ventana
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/logo/icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_user = new javax.swing.JLabel();
        label_password = new javax.swing.JLabel();
        txt_user = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        jButton_Acceder = new javax.swing.JButton();
        jLabel_Logo = new javax.swing.JLabel();
        jLabel_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_user.setFont(new java.awt.Font("Gadugi", 0, 16)); // NOI18N
        label_user.setForeground(new java.awt.Color(0, 0, 93));
        label_user.setText("Username:");
        getContentPane().add(label_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 298, -1, -1));

        label_password.setFont(new java.awt.Font("Gadugi", 0, 16)); // NOI18N
        label_password.setForeground(new java.awt.Color(0, 0, 93));
        label_password.setText("Password:");
        getContentPane().add(label_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 368, -1, -1));

        txt_user.setBackground(new java.awt.Color(240, 240, 240));
        txt_user.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        txt_user.setForeground(new java.awt.Color(7, 12, 67));
        txt_user.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_user.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 210, 35));

        txt_password.setBackground(new java.awt.Color(240, 240, 240));
        txt_password.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        txt_password.setForeground(new java.awt.Color(7, 12, 67));
        txt_password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_password.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_passwordKeyPressed(evt);
            }
        });
        getContentPane().add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 210, 35));

        jButton_Acceder.setBackground(new java.awt.Color(210, 210, 210));
        jButton_Acceder.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jButton_Acceder.setForeground(new java.awt.Color(0, 0, 93));
        jButton_Acceder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/login.png"))); // NOI18N
        jButton_Acceder.setText("Login");
        jButton_Acceder.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Acceder.setBorderPainted(false);
        jButton_Acceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AccederActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Acceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 440, 120, 38));
        getContentPane().add(jLabel_Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 350, 52));
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Evento del boton 'Acceder'
    private void jButton_AccederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AccederActionPerformed

        usuario = txt_user.getText().trim();
        pass = txt_password.getText().trim();

        if (!usuario.equals("") || !pass.equals("")) {

            try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection cn = DriverManager.getConnection("jdbc:mysql://bfsa3sxsr1yktijoeled-mysql.services.clever-cloud.com/bfsa3sxsr1yktijoeled", "ut5cg3puxyn4x8k7", "dexvZuEzWRPF4siweVO2");
                PreparedStatement pst = cn.prepareStatement("select estatus from usuarios where username = '" + usuario + "' and password = '" + pass + "'");
                ResultSet rs = pst.executeQuery();

                if (rs.next()) {
                    String estatus = rs.getString("estatus");

                    if (estatus.equals("Active")) {
                        dispose();
                        new InicioAdmin().setVisible(true);
                    } else if (estatus.equals("Inactive")) {
                        JOptionPane.showMessageDialog(null, "You are trying to access with a Inactive username", "Login error", JOptionPane.ERROR_MESSAGE);
                        limpiar();
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "Incorrect username or password.", "Login error", JOptionPane.ERROR_MESSAGE);
                    limpiar();
                }

            } catch (SQLException e) {
                System.out.println("Error en el boton Acceder " + e);
                JOptionPane.showMessageDialog(null, "Error en la conexión con la base de datos. Contacte con el Administrador del sistema.");
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Please introduce username and password.", "Login error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton_AccederActionPerformed

//Este evento hace lo mismo que el anterior, pero se dispara al pulsar la tecla Enter dentro del campo del password
    private void txt_passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_passwordKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {

            usuario = txt_user.getText();
            pass = txt_password.getText();

            if (!usuario.equals("") || !pass.equals("")) {

                try {
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection cn = DriverManager.getConnection("jdbc:mysql://bfsa3sxsr1yktijoeled-mysql.services.clever-cloud.com/bfsa3sxsr1yktijoeled", "ut5cg3puxyn4x8k7", "dexvZuEzWRPF4siweVO2");
                    PreparedStatement pst = cn.prepareStatement("select estatus from usuarios where username = '" + usuario + "' and password = '" + pass + "'");
                    ResultSet rs = pst.executeQuery();

                    if (rs.next()) {
                        String estatus = rs.getString("estatus");

                        if (estatus.equals("Active")) {
                            dispose();
                            new InicioAdmin().setVisible(true);
                        } else if (estatus.equals("Inactive")) {
                            JOptionPane.showMessageDialog(null, "You are trying to access with a Inactive username", "Login error", JOptionPane.ERROR_MESSAGE);
                        }

                    } else {
                        JOptionPane.showMessageDialog(null, "Incorrect username or password.", "Login error", JOptionPane.ERROR_MESSAGE);
                        txt_user.setText("");
                        txt_password.setText("");
                    }

                } catch (SQLException e) {
                    System.out.println("Error en el boton Acceder " + e);
                    JOptionPane.showMessageDialog(null, "Error en la conexión con la base de datos. Contacte con el Administrador del sistema.");
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Please introduce username and password.", "Login error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_txt_passwordKeyPressed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Acceder;
    private javax.swing.JLabel jLabel_Logo;
    private javax.swing.JLabel jLabel_Wallpaper;
    private javax.swing.JLabel label_password;
    private javax.swing.JLabel label_user;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_user;
    // End of variables declaration//GEN-END:variables

    public void limpiar() {
        txt_user.setText("");
        txt_password.setText("");
    }

}
