package ventanas;

import clases.BD;
import clases.Cliente;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

public class ModificarCliente extends javax.swing.JFrame {

    int cliente;
    BD bd;
/*
    //Variables utilizadas en el formulario
    String nombre_cliente, apellidos_cliente, dni_cliente, pasaporte_cliente, nacionalidad_cliente, tlf_cliente, email_cliente;
*/
    public ModificarCliente() {
        initComponents();

        cliente = Clientes.cliente;
        setSize(710, 660);
        setResizable(false);
        setTitle("Modificar cliente " + cliente);
        setLocationRelativeTo(null);

        //Impide que el programa se cierre al cerrar la ventana
        this.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        //Objeto BD
        bd = new BD();

        //Muestra la info del cliente al abrir la ventana
        cargarDatosCliente();

        //Imagen de fondo
        ImageIcon wallpaper = new ImageIcon("src/images/Wallpaper.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel_Wallpaper.getWidth(), jLabel_Wallpaper.getHeight(), Image.SCALE_DEFAULT));
        jLabel_Wallpaper.setIcon(icono);
        this.repaint();
    }
    
    //Icono de ventana
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/logo/icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_guardar = new javax.swing.JButton();
        txt_email = new javax.swing.JTextField();
        txt_tlf = new javax.swing.JTextField();
        txt_nacionalidad = new javax.swing.JTextField();
        txt_pasaporte = new javax.swing.JTextField();
        txt_dni = new javax.swing.JTextField();
        txt_apellidos = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        btn_cancelar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        label_id = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_guardar.setBackground(new java.awt.Color(255, 255, 255));
        btn_guardar.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        btn_guardar.setForeground(new java.awt.Color(29, 33, 123));
        btn_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/save.png"))); // NOI18N
        btn_guardar.setText("Save");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 490, 111, -1));

        txt_email.setBackground(new java.awt.Color(240, 240, 240));
        txt_email.setFont(new java.awt.Font("Gadugi", 0, 16)); // NOI18N
        txt_email.setForeground(new java.awt.Color(29, 33, 123));
        txt_email.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 560, 340, -1));

        txt_tlf.setBackground(new java.awt.Color(240, 240, 240));
        txt_tlf.setFont(new java.awt.Font("Gadugi", 0, 16)); // NOI18N
        txt_tlf.setForeground(new java.awt.Color(29, 33, 123));
        txt_tlf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txt_tlf, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 510, 150, -1));

        txt_nacionalidad.setBackground(new java.awt.Color(240, 240, 240));
        txt_nacionalidad.setFont(new java.awt.Font("Gadugi", 0, 16)); // NOI18N
        txt_nacionalidad.setForeground(new java.awt.Color(29, 33, 123));
        txt_nacionalidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txt_nacionalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 405, 200, -1));

        txt_pasaporte.setBackground(new java.awt.Color(240, 240, 240));
        txt_pasaporte.setFont(new java.awt.Font("Gadugi", 0, 16)); // NOI18N
        txt_pasaporte.setForeground(new java.awt.Color(29, 33, 123));
        txt_pasaporte.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txt_pasaporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 355, 200, -1));

        txt_dni.setBackground(new java.awt.Color(240, 240, 240));
        txt_dni.setFont(new java.awt.Font("Gadugi", 0, 16)); // NOI18N
        txt_dni.setForeground(new java.awt.Color(29, 33, 123));
        txt_dni.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txt_dni, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 305, 200, -1));

        txt_apellidos.setBackground(new java.awt.Color(240, 240, 240));
        txt_apellidos.setFont(new java.awt.Font("Gadugi", 0, 16)); // NOI18N
        txt_apellidos.setForeground(new java.awt.Color(29, 33, 123));
        txt_apellidos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txt_apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 255, 340, -1));

        txt_nombre.setBackground(new java.awt.Color(240, 240, 240));
        txt_nombre.setFont(new java.awt.Font("Gadugi", 0, 16)); // NOI18N
        txt_nombre.setForeground(new java.awt.Color(29, 33, 123));
        txt_nombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 205, 340, -1));

        btn_cancelar.setBackground(new java.awt.Color(255, 255, 255));
        btn_cancelar.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        btn_cancelar.setForeground(new java.awt.Color(29, 33, 123));
        btn_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/cancel.png"))); // NOI18N
        btn_cancelar.setText("Cancel");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 530, 111, -1));

        jLabel8.setFont(new java.awt.Font("Gadugi", 1, 30)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(29, 33, 123));
        jLabel8.setText("Customer modification:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 25, -1, -1));

        label_id.setFont(new java.awt.Font("Gadugi", 0, 16)); // NOI18N
        label_id.setForeground(new java.awt.Color(29, 33, 123));
        label_id.setText("...");
        getContentPane().add(label_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 156, -1, -1));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 490, 315, -1));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 135, 250, -1));

        jLabel9.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(29, 33, 123));
        jLabel9.setText("Ref.:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 155, -1, -1));

        jLabel10.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(29, 33, 123));
        jLabel10.setText("First name:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 205, -1, -1));

        jLabel11.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(29, 33, 123));
        jLabel11.setText("Last name:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 255, -1, -1));

        jLabel12.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(29, 33, 123));
        jLabel12.setText("ID Card:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 305, -1, -1));

        jLabel13.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(29, 33, 123));
        jLabel13.setText("Passport:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 355, -1, -1));

        jLabel14.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(29, 33, 123));
        jLabel14.setText("Nationality:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 405, -1, -1));

        jLabel18.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(29, 33, 123));
        jLabel18.setText("Contact details");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, -1, -1));

        jLabel15.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(29, 33, 123));
        jLabel15.setText("Phone:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, -1, -1));

        jLabel16.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(29, 33, 123));
        jLabel16.setText("E-mail:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 560, -1, -1));

        jLabel17.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(29, 33, 123));
        jLabel17.setText("Customer details");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 125, -1, -1));
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed

        int validacion = 0;
        int id_cliente = cliente;
        
        //Objeto Cliente
        Cliente cliente = new Cliente();
        cliente.setId_cliente(id_cliente);
        cliente.setNombre(txt_nombre.getText().trim());
        cliente.setApellidos(txt_apellidos.getText().trim());
        cliente.setDni(txt_dni.getText().trim());
        cliente.setPasaporte(txt_pasaporte.getText().trim());
        cliente.setNacionalidad(txt_nacionalidad.getText().trim());
        cliente.setTelefono(txt_tlf.getText().trim());
        cliente.setEmail(txt_email.getText().trim());
        
        //Validacion de los campos:
        if (cliente.getNombre().equals("")) {
            validacion++;
            txt_nombre.setBackground(new Color(255, 82, 82));
        } else {
            txt_nombre.setBackground(new Color(240, 240, 240));
        }

        if (cliente.getApellidos().equals("")) {
            validacion++;
            txt_apellidos.setBackground(new Color(255, 82, 82));
        } else {
            txt_apellidos.setBackground(new Color(240, 240, 240));
        }

        if (cliente.getDni().equals("")) {
            validacion++;
            txt_dni.setBackground(new Color(255, 82, 82));
        } else {
            txt_dni.setBackground(new Color(240, 240, 240));
        }

        if (cliente.getPasaporte().equals("")) {
            validacion++;
            txt_pasaporte.setBackground(new Color(255, 82, 82));
        } else {
            txt_pasaporte.setBackground(new Color(240, 240, 240));
        }

        if (cliente.getNacionalidad().equals("")) {
            validacion++;
            txt_nacionalidad.setBackground(new Color(255, 82, 82));
        } else {
            txt_nacionalidad.setBackground(new Color(240, 240, 240));
        }

        if (cliente.getTelefono().equals("")) {
            validacion++;
            txt_tlf.setBackground(new Color(255, 82, 82));
        } else {
            txt_tlf.setBackground(new Color(240, 240, 240));
        }

        if (cliente.getEmail().equals("")) {
            validacion++;
            txt_email.setBackground(new Color(255, 82, 82));
        } else {
            txt_email.setBackground(new Color(240, 240, 240));
        }

        if (validacion > 0) {
            JOptionPane.showMessageDialog(null, "Please complete all fields.", "Empty fields", JOptionPane.WARNING_MESSAGE);
        } else {
            if (bd.modificarCliente(cliente) == 0) {
                JOptionPane.showMessageDialog(null, "Error occurred while updating customer.");
            } else {
                JOptionPane.showMessageDialog(null, "Customer successfully updated.");
            }
            Clientes c = new Clientes();
            c.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        Clientes c = new Clientes();
        c.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_Wallpaper;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel label_id;
    private javax.swing.JTextField txt_apellidos;
    private javax.swing.JTextField txt_dni;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_nacionalidad;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_pasaporte;
    private javax.swing.JTextField txt_tlf;
    // End of variables declaration//GEN-END:variables

    public void cargarDatosCliente() {

        String[] info = bd.obtenerInfoCliente(cliente);

        label_id.setText(String.valueOf(cliente));
        txt_nombre.setText(info[0]);
        txt_apellidos.setText(info[1]);
        txt_dni.setText(info[2]);
        txt_pasaporte.setText(info[3]);
        txt_nacionalidad.setText(info[4]);
        txt_tlf.setText(info[5]);
        txt_email.setText(info[6]);
    }

}
