package ventanas;

import clases.BD;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.WindowConstants;

public class ModificarReserva extends javax.swing.JFrame {

    int reserva;
    BD bd;

    public ModificarReserva() {
        initComponents();

        setSize(600, 350);
        setResizable(false);
        setTitle("Modificar reserva");
        setLocationRelativeTo(null);

        //Impide que el programa se cierre al cerrar la ventana
        this.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        reserva = Reservas.reserva;

        bd = new BD();

        //Muestra la info del alojamiento al abrir la ventana
        cargarDatosReserva();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        label_ID = new javax.swing.JLabel();
        txt_precio = new javax.swing.JTextField();
        btn_guardar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        jDate_entrada = new com.toedter.calendar.JDateChooser();
        jDate_salida = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Reserva:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel2.setText("Entrada:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel3.setText("Salida:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel4.setText("Precio:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        label_ID.setText("...");
        getContentPane().add(label_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));
        getContentPane().add(txt_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 100, -1));

        btn_guardar.setText("Guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, -1, -1));

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, -1, -1));
        getContentPane().add(jDate_entrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));
        getContentPane().add(jDate_salida, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed


    }//GEN-LAST:event_btn_guardarActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed

        String[] info = bd.obtenerInfoReserva(reserva);

        try {
            SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
            Date fecha;

            fecha = formato.parse(info[1]);

            jDate_entrada.setDate(fecha);
            /*
            String[] info = bd.obtenerInfoReserva(reserva);
            label_ID.setText(String.valueOf(reserva));
            txt_entrada.setText(info[1]);
            txt_salida.setText(info[2]);
            
            
            // Obtención de fechas de entrada y salida con formato DATE
            Date entrada_input = info[0];//jDate_entrada.getDate();
            
            jDate_entrada.setDate("");
            
            Date salida_input = jDate_salida.getDate();
            System.out.println("Entrada: " + entrada_input);
            System.out.println("Salida: " + salida_input);
            
            long entrada_l = entrada_input.getTime();
            long salida_l = salida_input.getTime();
            
            java.sql.Date entrada = new java.sql.Date(entrada_l);
            java.sql.Date salida = new java.sql.Date(salida_l);
            
            System.out.println("Entrada: " + entrada);
            System.out.println("Salida: " + salida);*/
        } catch (ParseException ex) {
            Logger.getLogger(ModificarReserva.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_cancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarReserva().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_guardar;
    private com.toedter.calendar.JDateChooser jDate_entrada;
    private com.toedter.calendar.JDateChooser jDate_salida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel label_ID;
    private javax.swing.JTextField txt_precio;
    // End of variables declaration//GEN-END:variables

    public void cargarDatosReserva() {

        String[] info = bd.obtenerInfoReserva(reserva);

        SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
        Date fecha_entrada;
        Date fecha_salida;
        
        try {
            fecha_entrada = formato.parse(info[1]);
            jDate_entrada.setDate(fecha_entrada);
            fecha_salida = formato.parse(info[2]);
            jDate_salida.setDate(fecha_salida);
        } catch (ParseException ex) {
            Logger.getLogger(ModificarReserva.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        label_ID.setText(String.valueOf(reserva));
        //txt_entrada.setText(info[1]);
        //txt_salida.setText(info[2]);
        txt_precio.setText(info[3]);
    }

}
